name: NixOS (Plasma 6.2.5)

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:130595eba61081acde9001f43de3248d8888ac4a

      - name: Patch flake.nix
        run: sed -i 's/nixos-unstable/130595eba61081acde9001f43de3248d8888ac4a/g' flake.nix

      - name: Update flake.lock
        run: nix flake update

      - name: Build
        run: nix build