name: openSUSE Tumbleweed

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_kwin:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Refresh Packages
        run: zypper ref

      - name: Install Dependencies
        run: zypper in -y cmake-full gcc-c++ kf6-extra-cmake-modules kf6-kguiaddons-devel kf6-kconfigwidgets-devel kf6-ki18n-devel kf6-kcmutils-devel "cmake(KF6I18n)" "cmake(KF6KCMUtils)" "cmake(KF6WindowSystem)" "cmake(Qt6Core)" "cmake(Qt6DBus)" "cmake(Qt6Quick)" "cmake(Qt6Widgets)" libepoxy-devel kwin6-devel yaml-cpp-devel libxkbcommon-devel libevdev-devel

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DINPUTACTIONS_BUILD_KWIN=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j
